### ISSUE TITLE
Not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by autn** [atom/git-diff#152]
I'm using Ubuntu 18.04, installed the latest Atom version from store, and the Git Diff not working: don't show git branch and the changes.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by autn** [comment]
@thomasjo thanks for your correction!
