### ISSUE TITLE
Settings request: include whitespace in diff

### ISSUE THREAD

**Issue by simonjosefsson** [atom/git-diff#52]
When only adding whitespace to a file it shows as orange (modified) in the folder tree-view.
git-diff however ignores this whitespace.

I realize that the whitespace plugin by default mitigates this issue but it can still happen if the "ignoring whitespace only lines" is set. Or for those that disable it completely.

**Comment by peteruithoven** [comment]
This would be useful very. 
We just had quite some confusion when a file, created on OS X was changed on Windows, changing the type of new lines. Different editors gave different difference results.

**Comment by maxbrunsfeld** [comment]
This does sound useful, but I don't think we're likely to prioritize work on this anytime soon. I'm closing out old issues because we've [moved](https://github.com/atom/atom/pull/17993) this package into the main Atom repository. FWIW, This *is* something that we would most likely accept a PR for, if you submitted one that met our contributing guidelines. Thanks!
