### ISSUE TITLE
Add setting to ignore whitespaces in diff

### ISSUE THREAD

**Issue by abe33** [atom/git-diff#62]
I believe it would also require changes in the repository class in core so that we can pass cli options to `getLineDiffs` (`-w` in that case). 

See atom-minimap/minimap-git-diff#12

**Comment by josselinauguste** [comment]
Can't agree more !

**Comment by peteruithoven** [comment]
Also see: https://github.com/atom/git-diff/issues/52

**Comment by maxbrunsfeld** [comment]
This does sound useful, but I don't think we're likely to prioritize work on this anytime soon. I'm closing out old issues because we've [moved](https://github.com/atom/atom/pull/17993) this package into the main Atom repository. FWIW, This *is* something that we would most likely accept a PR for, if you submitted one that met our contributing guidelines. Thanks!
