### ISSUE TITLE
Setting request: diff against index instead of HEAD

### ISSUE THREAD

**Issue by UltCombo** [atom/git-diff#68]
E.g., [`git diff-files`](http://git-scm.com/docs/git-diff-files).

**Comment by UltCombo** [comment]
I had an error in the title and in the example command, sorry. Fixed these now.

**Comment by UltCombo** [comment]
Looks like we can use [`Repository.getLineDiffs`]( https://github.com/atom/git-utils#repositorygetlinediffspath-text-options)'s  `useIndex` option.
Would this setting be desirable? The setting could read like this:
- [ ] Diff against staged changes instead of the last commit.

**Comment by UltCombo** [comment]
A keybinding to toggle this setting would be really useful too, in my opinion.
What do you guys think?

**Comment by juantascon** [comment]
hi, instead of this option "Diff against staged changes instead of the last commit." it'd be better to have a field were you can point your diff to, it would default to HEAD but you'll be able to change it so it diffs against master or whatever base branch you use.

just fyi git gutter sublime extension allows this

**Comment by maxbrunsfeld** [comment]
It doesn't seem like there's a ton of interest in this, and I don't think we're likely to prioritize work on this anytime soon. I'm closing out old issues because we've [moved](https://github.com/atom/atom/pull/17993) this package into the main Atom repository. Thanks!
