### ISSUE TITLE
Request: Diff with tracking branch

### ISSUE THREAD

**Issue by jiku** [atom/git-diff#74]
I do WIP commits on branches to make sure changes are kept when updating from tracking branch (i.e. rebase 'feature' on 'master'), making changes to the working tree, etc. Would be nice to have a combined diff to note every change, including unmerged commits, from current to tracking branch. Beyond the scope of git-diff maybe?

**Comment by maxbrunsfeld** [comment]
I don't think we're likely to prioritize work on this anytime soon. I'm closing out old issues because we've [moved](https://github.com/atom/atom/pull/17993) this package into the main Atom repository. FWIW, This *may* be something that we would accept a PR for, if you submitted one that met our contributing guidelines. Thanks!
