### ISSUE TITLE
Diff list doesn't show the whole line of code in results

### ISSUE THREAD

**Issue by yay** [atom/git-diff#77]
LOC

<img width="345" alt="screen shot 2015-11-27 at 12 27 13 pm" src="https://cloud.githubusercontent.com/assets/1799756/11440412/8e093adc-9502-11e5-948d-77e3d920feda.png">

Diff List

<img width="576" alt="screen shot 2015-11-27 at 12 27 42 pm" src="https://cloud.githubusercontent.com/assets/1799756/11440414/91987942-9502-11e5-859d-cb88429b4f68.png">

The logic can be improved here. If the first line of a changed block shows little useful information (e.g. shorter than some number of characters, then check the next one and so on, if the changed block is multi-line.

**Comment by maxbrunsfeld** [comment]
This does sound useful, but I don't think we're likely to prioritize work on this anytime soon. I'm closing out old issues because we've [moved](https://github.com/atom/atom/pull/17993) this package into the main Atom repository. FWIW, This *is* something that we would accept a PR for, if you submitted one that met our contributing guidelines. Thanks!
